name: CheckCodeQuality

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  ktlint_pr_review:
    name: Ktlint -> github-pr-review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  ktlint_pr_check:
    name: Ktlint -> github-pr-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning

  detekt_pr_review:
    name: Detekt -> github-pr-review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: DominuS-RU/Detekt-Action@v1.14.2
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
          reviewdog_reporter: github-pr-review

  detekt_pr_check:
    name: Detekt -> github-pr-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: DominuS-RU/Detekt-Action@v1.14.2
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
          reviewdog_reporter: github-pr-check
          reviewdog_level: warning

  android_lint_pr_review:
    name: Android Lint -> github-pr-review
    needs: [detekt_pr_review, detekt_pr_check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Setup JDK 8
        uses: actions/setup-java@master
        with:
          java-version: 8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: Run Android Lint
        uses: dvdandroid/action-android-lint@master
        with:
          github_token: ${{ secrets.github_token }}
          lint_xml_file: app/build/reports/lint-results.xml
          reporter: github-pr-review

  android_lint_pr_check:
    name: Android Lint -> github-pr-check
    needs: [detekt_pr_review, detekt_pr_check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@master
        with:
          java-version: 8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: Run Android Lint
        uses: dvdandroid/action-android-lint@master
        with:
          github_token: ${{ secrets.github_token }}
          lint_xml_file: app/build/reports/lint-results.xml
          reporter: github-pr-check
          level: warning
